databases:
  - name: my-budget
    databaseName: my_budget_jah8
    user: my_budget_jah8_user

services:
  - type: web
    name: Friendly-Budget
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_budget_jah8
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
