databases:
  - name: my-budget
    databaseName: my_budget_jah8
    user: my_budget_jah8_user
    plan: free

services:
  - type: web
    name: Friendly-Budget
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-budget
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    plan: free
